repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format 

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        pass_filenames: false
        args: [
          "--config-file=pyproject.toml",
          "--explicit-package-bases",
          "--namespace-packages",
          "--ignore-missing-imports"
        ]
        additional_dependencies:
          - pydantic
          - pydantic-settings
          - pandera


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements